services:
  postgres:
    ports:
      - "5432:5432"
  pos-api:
    build:
      target: development
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      API_PORT: "3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
